### ISSUE TITLE
Unrecoverable Error on install

### ISSUE THREAD

**Issue by undercoverGuy** [IgorTimofeev/MineOS#169]
FTB Revelation, latest version

![image](https://user-images.githubusercontent.com/32490546/52905871-da1adc80-3240-11e9-9e0a-3dfea9a0600b.png)

**Comment by undercoverGuy** [comment]
nvm, didnt install openos before installing mineos

**Comment by undercoverGuy** [comment]
wait it still doesnt work

**Comment by M0RGaming** [comment]
The same error happened to me, and I looked through the commits and found that the latest commit got rid of the french localization files in 3d print.app in order to temporarily fix this, I forked the repo, then restored the second latest commit, and created a clone of the Pastebin script, then changed where the Pastebin script calls to my fork.

I hope you understand what I meant above, I was kind of rambling.

**Comment by M0RGaming** [comment]
Ignore what I said above, it turns out there is a simpler way to do it. Just disable language packs on the installation menu. If we want to have French, then we will just have to wait for the repo owner to re-add the files. (or do what I said above)

**Comment by IgorTimofeev** [comment]
FUCK!1111

Fixed, thanks
