### ISSUE TITLE
Can't move windows up

### ISSUE THREAD

**Issue by kevinkk525** [IgorTimofeev/MineOS#174]
I just installed MineOS and it looks awesome! However I can't move any windows up, only down, left and right.
Often the event seems to be cancelled and then applied to the objects at the position I wanted to move to window to.

**Comment by IgorTimofeev** [comment]
Meow?

![ScreenFlow](https://user-images.githubusercontent.com/11760002/56382626-7dc44100-6220-11e9-8727-0cd67fba63ac.gif)

**Comment by kevinkk525** [comment]
Ok I see I was not precise. The left side can move up but not the right side/top bar.
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/9607123/56415223-67080380-628d-11e9-9a9e-f61fcadb3e06.gif)

**Comment by IgorTimofeev** [comment]
Meow, it's because of one pixel free space by height. OpenComputers generates touch/drag events only if you've clicked on nearest neighbour pixel (at least if screen isn't in precise mode). OC pixels isn't a "real" pixels, it's a pseudographical costruct - so there's just not enough free space in Finder's top bar to detect that window needs to be moved upper.

It's just a one pixel:

![Снимок экрана 2019-04-19 в 12 37 09](https://user-images.githubusercontent.com/11760002/56418588-00d8ac00-62a0-11e9-905b-4b7715d9b539.png)

**Comment by kevinkk525** [comment]
Oh so it's an engine limitation that doesn't detect movement if it's outside the window? 
Hmm that's not so good as you would expect it to move up if it moves in any other direction..
Thanks for the clarification.

**Comment by IgorTimofeev** [comment]
Yes, OS UI library detects events in rectangluar objects only in their limits - so if you're dragging outside window, it stops moving. I think you demand too much from the pseudographic interface, because **real** UI frameworks works the same way, except **real** windows has much more free space in pixels to drag with upper :p

**Comment by kevinkk525** [comment]
Hmm I guess you are right.
It's impossible to implement as there is no way to distinguish between a drag start and a normal touch as both are normal touch events and only the first other pixel is a drag event which is already outside of the window.

**Comment by kevinkk525** [comment]
It just occured to me that it is in fact possible.
If you store the last touch event and process it with the draw event, you would know on which window the draw event started. This makes handling the event more complex but would have no problem processing draws to outside of the window limits.

**Comment by IgorTimofeev** [comment]
Of course I can. But I just don't care, meow. OS UI library's behavior is equal to modern frameworks, I don't want to develop something that will break commonly used concepts: one pixel is one pixel - it shouldn't be draggable. It's not draggable it real OSes - so it won't be draggable here.

The "real thing" I could do - is to add support for T3 screen precise touch/drag event mode with floating point coordinates, it would solve this problem

**Comment by kevinkk525** [comment]
That's fine.
I just wanted to point out that it is possible. It may not conform to how modern frameworks work but would achieve the same result as modern frameworks. So it really is same behaviour vs same implementation.
I only brought this up because the current doesn't conform to what I was expecting but now that I know the limitations I could of course live with it.

Nice cat ;)

**Comment by IgorTimofeev** [comment]
cyka blyad, same result would be here if OpenComputers will have the same screen resolution as real computers((99
