### ISSUE TITLE
MineIDE ate all four Tier 3.5 memories

### ISSUE THREAD

**Issue by atirut-w** [IgorTimofeev/MineOS#176]
It happens randomly while I was editing my ~3.8KB OCLinux kernel. When it happens, it would eat up all of the RAMs then crash itself and any other open programs

I even maxed out the server rack specs and this still happens, what now?

**Comment by IgorTimofeev** [comment]
The only thing you can is to disable autocompletion - it becomes a big fkin memory eater when editing files with tons of random words. If it's already disabled... ¯\_(ツ)_/¯

Btw I'm not really understand why this problem is actual for you: 3.8KB is a tiny file, IDE can handle with 40x bigger files with autocompletion enabled and without memory troubles:

![Снимок экрана 2019-04-25 в 12 03 49](https://user-images.githubusercontent.com/11760002/56723732-3541e180-6752-11e9-8dff-2dc145955855.png)

![Снимок экрана 2019-04-25 в 12 03 06](https://user-images.githubusercontent.com/11760002/56723681-1f342100-6752-11e9-89a4-c0996e5f3e3f.png)

**Comment by WattanaGaming** [comment]
Yet it crashes.

BTW holy shit that file is gigantic

**Comment by IgorTimofeev** [comment]
:((((((((((99999

I can only offer you a picture in compensation

![image](https://user-images.githubusercontent.com/11760002/56733635-6da0ea00-6769-11e9-9593-06f8d0c70802.png)

**Comment by WattanaGaming** [comment]
Totally belongs in r/aww

**Comment by CoolCat467** [comment]
@atirut-w This can likely be closed now

**Comment by IgorTimofeev** [comment]
![image](https://user-images.githubusercontent.com/11760002/124782263-c2953900-df4c-11eb-99b3-fadd6d5c5f10.png)
