### ISSUE TITLE
Tier II tablet compatibility

### ISSUE THREAD

**Issue by ThePoshTux** [IgorTimofeev/MineOS#177]
I am amazed by the amount of work that has been put into this, an outstanding job.
However, I have noticed issues with RAM usage even with 2 x tier 2.5 ram (the max for the tier 2 tablet) and User Interface scaling when using the tier two tablet. Perhaps a scaling option for the GUI could be implemented to account for screens larger or smaller than a tier 3 screen and using "update all" in the "app market" would do a few updates at a time if the ram is limited.

cheers for the great work

**Comment by IgorTimofeev** [comment]
Meow, UI scaling feature will be never added. Our team is too lazy to re-code every app with low-tier screen support, because OS development is finished. Some critical fixes will be done - but that's all.

And I don't completely understand what do you mean by scaling: all required interface elements just won't fit in lower resolution screens like 80x25. It's just not enough space to draw them. For example, Finder app contains a lot of vertically oriented buttons - favourites, network, mounts. How do you suggest to fit them?

Finally, this piece of shitty code wasn't designed for installing on tablets: it requires at least 2x tier 3 RAM modules to work correctly with disabled wallpapers, transparency and application icons - i.e. on "minimal" settings.

**Comment by ThePoshTux** [comment]
Completely forgot to leave my reply to this. When used with 2x tier 2.5 ram and all non necessary feature (icons and backgrounds) it functions rather well. However there was quite a bit of modifications I had to make to get it to a pleasant experience. Such as: removing unneeded icons from desktop to stop the "dock" from being overlapped and enabling the automatic disabling of uneeded modules. However there were a few bits that I wasn't able to fix, such as the reduced colour depth causing some text to be missing and having to maximize programs when started as they defaulted to higher resolutions. Perhaps the installer could be modified to always use reduced colour depth. Maybe have a switch to toggle between the standard install and a tablet friendly install that automatically uses the workarounds I took?

**Comment by IgorTimofeev** [comment]
Oh, you've suggested a very good idea for adding Dock hiding/showing functionality - that would be nice for lower resolutions. 

Reducing color depth during OS install/boot is not quite possible at this moment - especially for Tier 1 screens (any color that differs from #000000 is being drawn as "white"). Full OS code needs to be rewritten for supporting this features, and icons just won't be drawn cause of storing their own pixel data on disk. OF COURSE, I can write some additional code for Tier1 screens - it will check every pixel of image during loading and make it black/white in correct way, but performance will cry as a little bitch :(((((999

But this issue needs to be opened. Maybe some day of a hot summer... during eating some juicy meat and drinking cold sangria... ahhhh. Maybe this shit will be added.
