### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Dragonlord1005** [IgorTimofeev/MineOS#309]
Whenever I attempt to install it I get this screen 
![2021-01-08_11 28 04](https://user-images.githubusercontent.com/68302450/104051158-ed245600-51a4-11eb-8c67-644e0b5f5103.png)

**Comment by CoolCat467** [comment]
Interesting. Apparently the architecture of the computer can cause problems, and bit wise operators were apparently not completely supported until Lua 5.3. What is the set architecture of your computer's CPU?

**Comment by Dragonlord1005** [comment]
Lua 5.3

**Comment by CoolCat467** [comment]
Odd... Can you re-create the issue in detail? I would be happy to try to help you fix the problem.

**Comment by CoolCat467** [comment]
Pretty much, somewhere something is trying to use a variable for color that is a special object called a "NoneType Object", or "Nil". It represents nothing and sometimes zero, and doesn't support bit wise operations, which are done frequently with colors. I don't believe the installer does this, so steps to recreate your issue would be extremely helpful to assist you. Apparently some problems can occur when you don't have the most recent OpenComputers version too.

**Comment by Dragonlord1005** [comment]
Alright, I’ll see if I can replicate the issue in a new save

**Comment by cs-sugar** [comment]
I installed it successfully, but when I tried to use it, I reported that there was not enough memory. I used the server, and I used 4 and T3.5 memory.

**Comment by CoolCat467** [comment]
Does the hard-drive have enough space to install it?

**Comment by cs-sugar** [comment]
> Does the hard-drive have enough space to install it?

The hard disk is 4M, and I have formatted it, so there must be space to install it. However, the problem of insufficient memory will be reported after successful installation. Although it does not affect the use, the hard disk occupied in the setting is 35%, which is only reported when the machine is started. I have not seen it reported at other times, and it is also used very well. This problem was solved after I replaced another hard disk and re installed mineos.

**Comment by cs-sugar** [comment]
> > Does the hard-drive have enough space to install it?
> 
> The hard disk is 4M, and I have formatted it, so there must be space to install it. However, the problem of insufficient memory will be reported after successful installation. Although it does not affect the use, the hard disk occupied in the setting is 35%, which is only reported when the machine is started. I have not seen it reported at other times, and it is also used very well. This problem was solved after I replaced another hard disk and re installed mineos.

As soon as I opened the original hard disk, I would report an error. I was afraid, so I left the original hard disk idle. I plan to install openos or reload mineos in the future.

**Comment by CoolCat467** [comment]
People have programmed viruses for MineOS too you know. There are multiple instances of these able to be found in the MineOS app store, so don't randomly install stuff from there. I don't think it's a virus though, because most of the time they re-write the EEPROM too to make it harder to get rid of. It's probably just that particular drive. Good you got it fixed though. Issue can probably be closed now then.

**Comment by IgorTimofeev** [comment]
> The hard disk is 4M, and I have formatted it, so there must be space to install it. However, the problem of insufficient memory will be reported after successful installation. Although it does not affect the use, the hard disk occupied in the setting is 35%, which is only reported when the machine is started. I have not seen it reported at other times, and it is also used very well. This problem was solved after I replaced another hard disk and re installed mineos.

I had same problem when I was manually copy/pasting files to the Minecraft world save directory. OpenComputers HDDs has it's own free space markers, and any manual operation breaks them. Nothing to blame MineOS with

I.e. if you paste some large file to HDD dir via FTP/Exporer/etc, system would give you error like "not enough space", but .spaceUsed() method would return you "small" value like 148941
