### ISSUE TITLE
support vram

### ISSUE THREAD

**Issue by mckuhei** [IgorTimofeev/MineOS#313]
https://ocdoc.cil.li/component:gpu#video_ram_buffers

**Comment by CoolCat467** [comment]
MineOS has it's own double buffering protocol to best utilize the CPU/GPU by only rendering changes to the previous frame. If you want variable screen sizes (and therefore variable buffer sizes), there is already support for that too.

What do you mean by "support vram"?

**Comment by IgorTimofeev** [comment]
@CoolCat467 It's a new OpenComputers GPU feature. Nice idea btw, rendering should be really fast - but MineOS development has finished. I'll keep this issue open as reminder for some day (or someone)

**Comment by CoolCat467** [comment]
Ah, ok. Oh, and I guess with a good method of saving frames, that would be pretty fast. Obviously it would use up more hard drive space, being virtual ram, but with having way more hard drive space than ram you could handle large images much easier I would think.

**Comment by CoolCat467** [comment]
And virtual ram for not just the screen but also applications would make it possible to load tons more things, even though ram de-allocation is pretty good from what I've seen, like having full 3d games without worrying so much about the ram usage. Obviously OpenComputers computers are pretty slow, but still.

**Comment by IgorTimofeev** [comment]
Yeah, sounds good. Too sad that Screen lib has too much deep os optimizations that needs to be rewritted for vram...

Perfectly support for both systems is generally needed for old versions of the mod, so that, depending on the availability of VRAM methods, the system itself must decide which rendering system to use: through virtual buffers of RAM or through native VRAM

**Comment by IgorTimofeev** [comment]
Just tested VRAM buffers system - wtf, it's freaking slow. I mean ofk drawing to buffer and performing **gpu.bitblc()** on whole screen is way faster then basic loop of **gpu.set/fill/setBackground()**, but I was clearly expecting something more usable for serious graphical purposes. Moreover: the more changed pixels are contained in the VRAM buffer, the slower the **bitblc** operation will be, from which it follows that the VRAM buffers already have a built-in double buffering and pixel comparison methods.

Let's see what will be in the next release version of mod with this system. I sincerely hope that the performance will improve - because it is fucking not normal when a software solution is faster than a hardware one

**Comment by CoolCat467** [comment]
That is definitely not normal. That is truly unfortunate that the hardware implementation of VRAM is slow compared to software solutions.

**Comment by Kristopher38** [comment]
> Moreover: the more changed pixels are contained in the VRAM buffer, the slower the **bitblc** operation will be, from which it follows that the VRAM buffers already have a built-in double buffering and pixel comparison methods.

I know I'm necroposting but this is outright false. Call budget cost of a bitblt operation is proportional to the VRAM buffer size that's being bitblt'ed (assuming it's been written to since last bitblt call, otherwise it's almost free). From my experience, the most efficient way of rendering with VRAM buffers is to have a buffer the size of a screen and render everything each frame there (after all draw calls to a buffer are almost free), then bitblt it to the display. Depending on your use case you could get 20FPS, see e.g. here https://www.youtube.com/watch?v=DuxJvOBze9k

**Comment by CoolCat467** [comment]
Draw code video links to: https://pastebin.com/h9zUNB1x

**Comment by IgorTimofeev** [comment]
> I know I'm necroposting but this is outright false. Call budget cost of a bitblt operation is proportional to the VRAM buffer size that's being bitblt'ed 

Yea, you're correct, it can be checked [here](https://github.com/MightyPirates/OpenComputers/blob/ad76e2a54a9d7f9fdede851b2491972641b71f8f/src/main/scala/li/cil/oc/server/component/GraphicsCard.scala#L196-L209). But who gives a fuck about the details if they don't fix the problem? The main charm of the current software solution is not so much in drawing only the changed pixels, but in combining neighboring ones into single `gpu.set()` call and grouping them by color, which reduces tons of gpu operations & saves time

However, I don't think you'll take my word for it, so I've adjusted screen lib with VRAM support and... system become almost unusable xd

[test.zip](https://github.com/user-attachments/files/16468928/test.zip)

> Depending on your use case you could get 20FPS or more, see e.g. here https://www.youtube.com/watch?v=DuxJvOBze9k (I suspect this runs at more than 20FPS despite the counter in the video saying otherwise, time calculation probably only has tick resolution in that demo)

This guy is using the simplest case possible, where the pixel colors are constant and don't change during rendering, so it doesn't take long to flash the buffer to the screen - that's the secret

Btw screens aren't capable to give more then 20 fps even in theory, since tile entities in Minecraft are being updated only 20 times per second. Sof if your code is perfect and doesn't consume components call budget - then yes, you can get close to 20 fps, depending of scene complexity
