### ISSUE TITLE
Fresh Install, needs updates?

### ISSUE THREAD

**Issue by snaildos** [IgorTimofeev/MineOS#326]
Yo! ^w^, After installing MineOS, opening the appstore, heading too the updates, everything needs updates?
huh?
Maybe can someone check dis out!
Hope to hear from someone soon.

**Comment by IgorTimofeev** [comment]
Meow, In fact, everything is installed immediately with the latest version. Since the AppMarket database is located on my home host, I did not want to put it to additional load with obtaiting versions during OS installation, and I also wanted to get rid of the possible host unavailability. So the first "global" update in market in simply updates the version numbers cache

**Comment by snaildos** [comment]
Ah. This all makes sense. Why does updating take a hour sometimes tho?

**Comment by IgorTimofeev** [comment]
A hour? Wtf, it should be ~1-2 min max. Internet cards are slow, but not like this :D

**Comment by snaildos** [comment]
Yes- that's why I'm sending a issue :p

Some suggestions:


1. A MineOS discord, for people too collaborate.

2. A inbuilt database in mineos, for packages, (like APT). This way, 
MineOS knows what's going on. I think this would be the best solution.

I also have a suggestion, of separating system file/apps to be upgrade 
via the app store. Instead, a "Update OS" app should be on the 
desktop/settings.

I'd like too see these in the future, hopefully.

Regards,

SnailDOS :p

**Comment by snaildos** [comment]
Would you be *planning* too separate the sys files from app store?
I'm only asking this because, APPS / System are different. Totally different.
"Update OS" will download the files it needs, (If your homelab can't handle it, I am happy too host). Then, it would update the files, and trigger a app store update too update all apps.

App Store, I'd think of it as a "extension" too MineOS. These should be different.

A discord server for MineOS, would be awesome too have, since, many people use discord these days.

Inbuilt database like APT, Would be awesome, since it can cache all of this client side.

**Comment by snaildos** [comment]
> A hour? Wtf, it should be ~1-2 min max. Internet cards are slow, but not like this :D

I see! It's because you used the enhanced CPU, 1 hour is a bit of a over reaction, it usually takes 10-30 mins sometimes. When unloading chunks and running around it takes hours.

**Comment by IgorTimofeev** [comment]
@snaildos 

> A MineOS discord, for people too collaborate

No thanks, I don't care about people and their collaboration, especially using tons of trashchats in Discord/IRC. Especially when MineOS development was finished 2 years ago

> A inbuilt database in mineos, for packages, (like APT)

This "database" already exists and it's called "AppMarket". It caches every icon/description/other stuff to local machine, so the only difference is UI instead of console

> This way, MineOS knows what's going on

What do you mean? The only thing MineOS doesn't know is the actual apps/libs versions list after clean OS installation. Main reason was descriped earlier: I don't want to put additional load to my home host for someone who can't wait 1 more minute for full update. And I also don't want to make OS deeply-dependent from AppMarket, because GitHub is the most reliable downloading source

> I also have a suggestion, of separating system file/apps to be upgrade via the app store. Instead, a "Update OS" app should be on the desktop/settings

No, because some updated file/app may require newest version of system library that will not be updated because of separation. Wtf is so bad about "global update" button? Personally, I don't give a fuck about waiting 1 minute for the apps to update or 2 minutes for global system update. Nothing about "2 hours" like you said.

If something is wrong with AppMarket downloading speed - don't use it. Or just download the only applications you want to update/install. Every depenency will be automatically updated either

> I see! It's because you used the enhanced CPU

What is "enhanced CPU"? Tier 1-2? Does anyone still craft this garbage for anything other than drones/robots nowadays?

> When unloading chunks and running around it takes hours.

What's the problem about using chunkloaders or just fucking waiting for update to complete in the same chunk? Update can't be slower then clean MineOS installation because of using same scripts from same host. If clean installation is THAT slow... F
