### ISSUE TITLE
MineOS on Floppy?

### ISSUE THREAD

**Issue by PublicVoidUpdate** [IgorTimofeev/MineOS#330]
Is it possible to install the installer on a floppy like openos or plan9k?

**Comment by IgorTimofeev** [comment]
Hell knows. You can try do it yourself:
https://github.com/IgorTimofeev/MineOS/blob/master/Installer/Main.lua

**Comment by MrFredber** [comment]
I tried to do this, but the maximum I was able to compress the system to 600 kb, and the floppy fits 512 kb. the problem is that the system itself weighs about 150 kb, the rest is huge libraries, such as the GUI

**Comment by MrFredber** [comment]
*I tried to fit all system

**Comment by PublicVoidUpdate** [comment]
What about just the installer?

**Comment by IgorTimofeev** [comment]
@MrFredber So it was about the entire system, and not just about the installer? Then the problem is more complicated: you need to use some self-extracting script like [this ](https://oc.cil.li/topic/511-crunch-break-the-4k-limit/) to fit all the pictures and libraries in one binary string

If you only need to put the installer on the floppy disk, then this does not make much sense, because it will upload all files over the Internet anyway

**Comment by PublicVoidUpdate** [comment]
@IgorTimofeev I was planning on putting the installer on a floppy so wouldn't have to remember/write down the install code and to make it a bit more immersive

**Comment by MrFredber** [comment]
@IgorTimofeev I wanted to do something like Windows PE. And i can talking on the Russian language.

**Comment by IgorTimofeev** [comment]
@PublicVoidUpdate Ah, ok. But if you're going to use installer floppy from OpenOS, then you will have to modify the original installer, because for some secret reason, OpenOS removes 3 global variables (computer/component/unicode) during initialization:

https://gist.github.com/IgorTimofeev/5ca3ced96d311d42c5c09fa7f2975be5

**Comment by IgorTimofeev** [comment]
@MrFredber Дело благородное, но дохуя геморрное. Если грузиться с флоппи после распаковки данных, то все системные библиотеки/иконки должны располагаться в каком-либо "временном" компоненте файловой системы для корректной работы. Можно запариться и замутить что-то типа RAMDisk, создав фейковый прокси filesystem, для чего потребуется минимум 740 кбайт оперативы на максимально "чистую" версию майноськи без обоев и дополнительных приложений

**Comment by PublicVoidUpdate** [comment]
I put the file on afloppy, but when I use the install command it just adds it to /mnt/76d/. And doesn't boot up into the installer even when i reboot

**Comment by PublicVoidUpdate** [comment]
@IgorTimofeev  how would I make this file autorun after installation instead of manually having to run it?

**Comment by MrFredber** [comment]
@IgorTimofeev Я же правильно понимаю, что твоя Mine OS не использует стандартную папку lib?
P.S. я в lua не такой знаток и поэтому не знаю, что такое прокси

**Comment by IgorTimofeev** [comment]
@MrFredber Эта "стандартная" папка lib "стандартна" только для OpenOS, а не для OpenComputers. MineOS работает с OpenComputers, а не другой ОС
