### ISSUE TITLE
some question with wide char.

### ISSUE THREAD

**Issue by kebufu** [IgorTimofeev/MineOS#340]
are you using `#` not `unicode.len()`?
![QQ截图20210417194720](https://user-images.githubusercontent.com/31839741/115112032-06b01780-9fb6-11eb-9add-9489404b02aa.png)

**Comment by MrFredber** [comment]
Why are you using emulator? And rephrase your question.

**Comment by kebufu** [comment]
> Why are you using emulator? And rephrase your question.

That's not a matter

**Comment by IgorTimofeev** [comment]
> are you using # not unicode.len()

No, screen lib doesn't consider string length and **width**, it operates with horizontal scanlines of characters with same color properties and calling gpu.set() function. If you try to set wide character at x/y, you will see it fits more then 1 pixel.

Wide characters are not (and will not be) supported by screen lib. Why? Because I don't care about other languages and want to see better peformance without such checking for every pixel of screen buffer.
