### ISSUE TITLE
Interval event keeps running after I close the window?

### ISSUE THREAD

**Issue by dom11990** [IgorTimofeev/MineOS#400]
I'm having some trouble with the event setup. I'm trying to make a simple timer that does a check every 5 seconds. For now I'm just printing some text to the screen and that works fine using the event.addHandler(myfunct,5). What is strange, however, is that after I close my GUI, the event continues to trigger every 5 seconds. Should it not stop after the GUI closed? How do I do this properly? That is to say, how to set up a "timer event"? Is there a means of detecting when a user closes the window via the red button in the top left so that I can unregister the handler? Thanks for any help!

**Comment by IgorTimofeev** [comment]
Yeah, event.addHandler is **global** and have nothing common with windows and GUI. It's a system library and should be used mostly in low-level coding, like "Keyboard.lua", background daemons or something like that

You should attach an event handler to window if you don't need it after window closing:

```lua
local interval = 5
local uptime = computer.uptime()
window.eventHandler = function()
  if computer.uptime() - uptime() > 5 then
    -- Do your stuff
    uptime = computer.uptime()
  end
end
```

Or, if for some reason you need global event.addHandler:

```lua
local handler = event.addHandler(...)

local overrideWindowRemove = window.remove
window.remove= function(...)
  overrideWindowRemove (...)
  event.removeHandler(handler)
end
```

**Comment by dom11990** [comment]
Hey @IgorTimofeev, thanks for the reply! Also, this is an amazing mod, great work!

I looked in the documentation but could find no mention of the remove function other than it is called to delete the window. I wasn't sure it would work by simply overwriting it. I'm a lousy lua writer but to me it seems you simply overwrote the standard remove function with an alternative that unregisters the global handler and calls the default remove. Is this correct? This makes sense to me. I was unaware that the event library calls persisted after the program runs. Good to know, thanks. 

I tried it with the object bound event handler (I used workspace instead of window, saw that somewhere else) but it still seems to persist even after I close the GUI. However, when I switch to your method, using window everything works great, assuming I called workspace:start(0). Can you explain what exactly a workspace is? The Wiki just says its a fullscreen container. Is it essentially a singleton? The top level MineOS container that all windows share? Therefore, if I have 2 running programs, if each overwrites the workspace handler one handler is "lost"? Thanks for your help!

**Comment by IgorTimofeev** [comment]
> I looked in the documentation but could find no mention of the remove function other than it is called to delete the window

:remove() method is inherited from Object that was added to Container, beacuse any Window is an Object:

![image](https://user-images.githubusercontent.com/11760002/142071844-5efcacde-70bc-49ed-a8f3-69d98a648464.png)

> I'm a lousy lua writer but to me it seems you simply overwrote the standard remove function with an alternative that unregisters the global handler and calls the default remove. Is this correct?

Yes, you're correct. It's like method overriding in any other language. Lua just don't have such a feature:

```C#
public class Object {
  public virtual void Remove() {
    // Code that removes object from parent container
  }
}

public class Window : Object {
   public override void Remove() {
    base.Remove();

    // Do some additional stuff after removing window object from parent container
  }
}
```

> I tried it with the object bound event handler (I used workspace instead of window, saw that somewhere else)

Ah, this explains why your event handler was not being deleted. The entire OS is just one large GUI.workspace, it works via Single Thread Application concept. This means OS workspace is **global** for every application window being added to it.

To make this work, you should attach your event handlers to window using overriding, because every window already have built-in event handler for moving it around workspace using mouse. Or, alternatively, you can attach your event handler to any "free" child object of window, if overriding doesn't seems like "pure" coding:

```lua
local workspace, window, menu = system.addWindow(GUI.filledWindow(1, 1, 60, 20, 0xE1E1E1))

local interval = 5
local uptime = computer.uptime()

-- You can do it like that
local overrideWindowEventHandler = window.eventHandler
window.eventHandler = function(...)
  overrideWindowEventHandler(...)

  if computer.uptime() - uptime > interval then
    -- Do your stuff
    uptime = computer.uptime()
  end
end

-- Or like that (GUI.filledWindow has backgroundPanel object)
window.backgroundPanel.eventHandler = function(...)
  if computer.uptime() - uptime > interval then
    -- Do your stuff
    uptime = computer.uptime()
  end
end
```

And no, workspace is not a singleton. If you create it and call :start() - if will block current thread (it's only one, hehe) and start waiting for events. For example, this allows you to create standalone applications that do not redraw the OS background widgets, thereby freeing up already limited computer resources

**Comment by dom11990** [comment]
Great thanks again!
