### ISSUE TITLE
(not issue) How did you make the server?

### ISSUE THREAD

**Issue by cadergator10** [IgorTimofeev/MineOS#504]
I didn't know of a better way to contact you, so I just am using the mineos issue thing. I am wanting to make a server that my programs can sync up with to download stuff, very much like the App Market on MineOS. I was wondering if there were any tips or information on how you made yours?

**Comment by IgorTimofeev** [comment]
You will need 3 things: a server (similar to where websites are hosted), a database where all your applications will be stored, and an API that OpenComputers will access

The operating system of the server doesn't really matter, but I'll assume you'll be using some "easy-to-use" linux distribution like debian/ubuntu

1. Install a database management system. If this is your first experience with databases, then I highly recommend using MariaDB/MySQL because of its simplicity. You can also check out a couple of guides on YouTube to understand why the fuck do you need it

2. Install a web server such as Nginx/Apache with link to any programming language convenient for you such as PHP/Python. Thes two guys will process requests from OpenComputers and send a response with data back to it

3. Set up remote access to the database and web server to always be able to connect to the server from your home computer

4. Install any PhpStorm/PyCharm development environment on your home computer. Usually you can write API code and work with the database directly in IDE without having to download a lot of separate software to do that. So if you don't want to suffer from butthurt - install an IDE

5. Design the database for your needs. If you want to create some kind of app store - you will need need a user accounting system with logins/passwords, as well as a list of publicly hosted applications

6. Develop an API that connects to the database and provides basic functionality for registering/authorizing, getting a list/creating/modifying/deleting applications in the store on behalf of any owner user

The communication protocol between the server and the client via API is not particularly important: JSON is simple and most commonly used, but you can choose any on your taste - XML, for example

When writing a public API, always keep potential security risks in mind. Google a couple of guides of SQL injections, as well as measures to counteract them (hint: in 99% of cases, prepared SQL queries are more than enough)

7. Write a client application for OpenComputers that can communicate with your API, allowing you to register/login/download applications

If you need checkinf for updates of previously downloaded applications, store their version in the database, increase the version value with each update and keep downloaded version info on client. Thus, the client can always understand whether he has downloaded an up-to-date or outdated version of the application

**Comment by cadergator10** [comment]
Thank you so much! I'll look into this :)
