### ISSUE TITLE
I can install my system

### ISSUE THREAD

**Issue by awmc233** [IgorTimofeev/MineOS#518]
I can't install my system, I followed the instructions to copy the command on the website, but it didn't work, the computer said computer halted after reboot What should I do (I'm a Chinese, so my GitHub here is very unstable)
![image](https://user-images.githubusercontent.com/87456168/212524107-b0dee6ec-a219-48b9-8091-f985f042481e.png)

**Comment by IgorTimofeev** [comment]
The problem is related to the fact that the EEPROM firmware completed its work without errors. Most likely, in your case, EEPROM is simply empty, because firmware code just wasn't downloaded

Unfortunately, the installer downloads all the necessary files directly from github via direct links. You can use a proxy for installation if you are not too lazy to mess with it

But if you still REALLY want to try this, and there are no other options left, then:
1) Run OpenOS
2) Run `edit /tmp/eeprom.lua`
3) Copy [MineOS EEPROM firmware](https://github.com/IgorTimofeev/MineOS/raw/master/EFI/Minified.lua) and paste it with `middle mouse button` or `insert key` to in-game code editor. Don't forget to save it!
3) Run `flash -q /tmp/eeprom.lua && reboot`
4) Turn off in-game computer
5) Unzip the [MineoS HDD dump](https://github.com/IgorTimofeev/MineOS/releases/download/HDD/MineOS.zip) to the root of your in-game HDD from the ~/.minecraft/saves/**\<world save name\>**/opencomputers/**\<in-game HDD UUID\>**/
6) You will probably need to exit-enter your world in singleplayer or restart your server to update the mod's disk cache (you can set `bufferChanges=false` in the mod's config to disable caching for better coding experience in future)
7) Profit

**Comment by awmc233** [comment]
Thank you very much, the friendship between China and Russia endures (I am using machine translation, the translation may not be accurate)


Спасибо большое, дружба между Китаем и Россией продолжается (я использую машинный перевод, перевод может быть неточным)

**Comment by IgorTimofeev** [comment]
![image](https://user-images.githubusercontent.com/11760002/212620482-8c568069-0898-4815-9b7f-956f0597d860.png)

**Comment by MrFredber** [comment]
> ![image](https://user-images.githubusercontent.com/11760002/212620482-8c568069-0898-4815-9b7f-956f0597d860.png)

+

**Comment by awmc233** [comment]
Sorry to bother, I want to ask again,
![image](https://user-images.githubusercontent.com/87456168/212622687-8abba3bf-d1cf-40b6-9c23-c39b6ab91d33.png)
 this is my server's files under /.minecraft/saves/<world save name>/opencomputers/<in-game HDD UUID, do I need to delete them? And do I need to unzip the .zip package I downloaded?

**Comment by MrFredber** [comment]
Это и есть твоя установленная система. Здесь ничего удалять не надо.
Раз ты уже распаковал MineOS.zip, то ничего больше распаковывать не нужно

**Comment by IgorTimofeev** [comment]
> do I need to delete the

Yes

> And do I need to unzip the .zip package I downloaded

Yes, like this

![image](https://user-images.githubusercontent.com/11760002/212665784-3b7a6b29-2816-49bf-82d4-09f8d93ba88a.png)

**Comment by MrFredber** [comment]
Aah, I'm blind. Excuse me :D

**Comment by awmc233** [comment]
Thanks!
