### ISSUE TITLE
Feature request: Installer (read desc)

### ISSUE THREAD

**Issue by Def-Try** [IgorTimofeev/MineOS#539]
It would be cool, if MineOS had high level installer that at least checks if your system is compatible sith system, before flashing your EFI.
It can also shorten the command.
From: wget, flash, reboot
To: wget

**Comment by MrFredber** [comment]
In installer you normally can check only tier of GPU and availability of an internet card, because amount of RAM can be changed in mod configuration.
wget command only downloading a file. You will do more steps of starting installer manually instead of just copy, paste and clicking buttons in installer.

**Comment by Def-Try** [comment]
1.Why not to do at least these checks?
MineOS does depends on 3 ties of almost everything.
T3 GPU can work in 4 bit color palette(i dont remember exactly, maybe 8 bit)
Only T3 screen can use subpixel mode for mouse movements.
We do not care about RAM tier, if it can run mineos -> check available ram
We do not care about disk tiers, if it can store mineos -> check available space
Check availability of internet card
Also I think there is a way to check processor tier, but idk

2. I did not said that installation will be moved to openos. I just want pre-installer that will check your pc for compability, maybe download some files, flash your eeprom if it is and reboot

**Comment by PublicVoidUpdate** [comment]
Screen isnt too important either, ive run tablets with MineOS

**Comment by MrFredber** [comment]
You can do that script on your own and replace command line with downloading and running script. Processor Tier can't be checked. MineOS can work on Tier 2 and 3 screen.
In script you can check the minimal requirements and if the pc/tablet is compatible - then download an installer and flash it. If not - print to the console what components are missing or wrong.
Code this script is simple, but Igor won't do it, because he doesn't need it.
Only you or someone else can do that.

**Comment by IgorTimofeev** [comment]
> before flashing your EFI

Flashing was added for "clean" installation from other OSes like OpenOS, because it substitutes original computer.pullSignal method with custom one, creating process/coroutines problems that I'm sick of solving

> Why not to do at least these checks?

Bro, you can add them, it's open source. If you want a preliminary check without flashing EEPROM, then I think it's worth making a separate installer script for OpenOS, which will simply print() all the necessary information. Or we can make a universal check that will display the relevant information after EEPROM flashing without print()
