### ISSUE TITLE
Bug While Installing Possibly with OC it self tho.

### ISSUE THREAD

**Issue by KittenPixel-cell** [IgorTimofeev/MineOS#596]
**Describe the bug**
Installing causes a bug
 `﻿
HTTP request failed: /bin/wget.lua:72: sun.security.validator.ValidatorException : PKIX path building failed: sun.security.provider.certpath. SunCertPathBuilderException: unable to find valid certification path to requested target
`

**To Reproduce**
1. Just Install It

**Expected behavior**
It Installing it

**Screenshots**
![image](https://github.com/IgorTimofeev/MineOS/assets/79544605/809e820e-0b84-45aa-b7cf-6b164a073863)

**Minecraft and OpenComputers version**
1.8.3

**Comment by KittenPixel-cell** [comment]
Is it mabye github?

**Comment by CoolCat467** [comment]
This is a duplicate of https://github.com/IgorTimofeev/MineOS/issues/593. Basically the issue is that your computer's SSL certificates are out of date. Other people had this same issue in a different piece of software on stack overflow, and the solution they used will probably help you as well: https://stackoverflow.com/questions/21076179

**Comment by KittenPixel-cell** [comment]
How do I update it the stackoverflow did not help

**Comment by IgorTimofeev** [comment]
Update Java or web certs
