### ISSUE TITLE
Both Pastebin and wget links do not work and i cant install MineOS. minecraft 1.12.2

### ISSUE THREAD

**Issue by GeorgiSP2009** [IgorTimofeev/MineOS#600]
**Describe the bug**
When i paste the pastebin or the wget link in the terminal, on both i get error codes.
I have all minimum requirements of the computer
When i paste the wget link, a blue screen comes up that says error computer halted 
Minecraft 1.12.2
OpenComputers 1.8.3

![2024-04-10_18 24 10](https://github.com/IgorTimofeev/MineOS/assets/144341956/c0c20df6-4c0d-4ba6-aa83-372ef4d45df0)

**Comment by Bumer-32** [comment]
duplicate #593 not mineOS problem.
Try updating your computer's SSL certificates.

**Comment by GeorgiSP2009** [comment]
But how to update them on Mac, because online i can't find or understand the instructions

**Comment by Bumer-32** [comment]
Sorry but I newer use Mac. Try to ask it on forums.

**Comment by Smok1e** [comment]
That problem is known and not related to MineOS itself; The only thing we can do is to reference to related [stackoverflow question](https://stackoverflow.com/questions/21076179) as we can't reproduce the situation. Since this problem became really popular recently, if we can solve it, we will make detailed instruction. For now all i can suggest is to try reinstalling java

**Comment by Bumer-32** [comment]
Some new info: it can be outdated java? really try to reinstall it with last version from official website
