### ISSUE TITLE
I have a problem 

### ISSUE THREAD

**Issue by Leonardo5681** [IgorTimofeev/MineOS#615]
Hi, I found an old world of mine from 2021 where I used opencomputers and mineos. Since I didn't remember what was inside the PCs, I decide to turn them on, but they have a password that I don't remember..
Is there a way to find out the password or a file saved somewhere containing the password? I hope you can help me. Thank you and good day

**Comment by CoolCat467** [comment]
Not possible to retrieve password, MineOS is actually pretty awesome and hashes passwords with SHA-256. Totally possible to read hard drive data though, nothing is encrypted because that would add a lot of overhead to reading files, so you could probably install MineOS new on a separate drive and then copy all the files except the user config one over from the old disk to the new one.

**Comment by Smok1e** [comment]
To reset your password, firstly, find your opencomputers' hdd id by hovering mouse on it: 
![image](https://github.com/IgorTimofeev/MineOS/assets/33802666/cb841e19-f9c9-4bf0-b026-229b48e0fccc)

Then, go to file in your `save directory/opencomputers/<hdd id>/Users/<username>` and find line starting with "securityPassword=" and change corresponding value to `"9f2918462af0d41319d23a02394bbb658be53ffdb0f20764714ab44adb47a32c"`:
![image](https://github.com/IgorTimofeev/MineOS/assets/33802666/89bec0fd-8274-4ba3-9100-6dd3b19b878a)

Now you will be able to log in to MineOS by entering the password `test`.

**Comment by Smok1e** [comment]
BTW, you can just remove this line in Settings.cfg to disable password at all
