### ISSUE TITLE
Cannot install mineos

### ISSUE THREAD

**Issue by Negr550** [IgorTimofeev/MineOS#652]
Im trying to download a mineOS, but im getting error while downloading.
I'm using 1.7.10-1.8.6+ version of open computers.
Im used both variants of installing:link and pastebin
![IMG_2024_12_11_12_29_08_2415683292112684977149](https://github.com/user-attachments/assets/a92262dc-d9ce-4a28-bedd-a5744c008db0)

**Comment by Smok1e** [comment]
https://github.com/IgorTimofeev/MineOS/wiki/SSL-issue

**Comment by Smok1e** [comment]
> > https://github.com/IgorTimofeev/MineOS/wiki/SSL-issue
> 
> Hi, i forgot to say, im using java 17, sorry

The error shown on screen says that SSL certificates used by your java installation are outdated. No matter what major java version you are running on. I have no idea what exact version you are using, but you can check it in F3 menu at the right top corner, as shown [here](https://github.com/IgorTimofeev/MineOS/wiki/SSL-issue). **If it is lower than 17.0.12, update it**. Otherwise i can't help you.

**Comment by Negr550** [comment]
> > > https://github.com/IgorTimofeev/MineOS/wiki/SSL-issue
> > 
> > 
> > Hi, i forgot to say, im using java 17, sorry
> 
> The error shown on screen says that SSL certificates used by your java installation are outdated. No matter what major java version you are running on. I have no idea what exact version you are using, but you can check it in F3 menu at the right top corner, as shown [here](https://github.com/IgorTimofeev/MineOS/wiki/SSL-issue). **If it is lower than 17.0.12, update it**. Otherwise i can't help you.

I've updated java to 17.0.12 version, but it didnt helped
